import { useLocale } from '../i18n/LocaleContext';

const en = {
  overview: 'Overview', fuelReport: 'Fuel consumption', efficiencyReport: 'Generator efficiency', reportsIntro: 'Service planning, early condition changes, and measured fuel performance.',
  allGenerators: 'All generators', selectGenerator: 'Select a generator', customRange: 'Custom dates', fromDate: 'From', toDate: 'To', refresh: 'Refresh', invalidDates: 'Choose a valid start and end date.',
  noGenerators: 'Add a generator to start reporting.', unavailable: 'Unavailable', noData: 'No valid measurements are available for this period.', loadingReport: 'Loading report…', exportReport: 'Export report (CSV)',
  period: 'Period', recordFuelMovement: 'Record fuel movement', movementHelp: 'Record a positive refill or negative transfer from this generator’s own tank. Shared tanks cannot attribute fuel to one generator.', movementDate: 'Movement time', movementLitres: 'Litres (+ refill / − transfer)',
  maintenanceDueBanner: '{{overdue}} overdue service tasks · {{soon}} due soon',
  maintenanceCompliance: 'Maintenance compliance', monitoredCondition: 'Monitored condition', dataCoverage: 'Data coverage', complianceHelp: 'Configured tasks that are not overdue.', conditionHelp: 'Observed operating condition; not a certification of physical health.', coverageHelp: 'Usable readings within the selected history.',
  healthy: 'No sustained issue detected', attention: 'Attention required', critical: 'Urgent attention required', insufficient_data: 'Insufficient data',
  taskSchedules: 'Preventive service schedule', taskScheduleHelp: 'Use the engine manufacturer’s intervals. Hours or calendar time, whichever comes first, determines the due date.', addTask: 'Add service task', editTask: 'Edit task', archiveTask: 'Archive task', archiveConfirm: 'Archive this service task? Its completion history will be retained.',
  maintenanceDateScope: 'Selected dates filter readings, findings history and completed services. Task deadlines and open findings remain current.',
  taskName: 'Task name', component: 'Component', intervalHours: 'Interval (running hours)', intervalDays: 'Interval (calendar days)', manufacturerReference: 'Manufacturer / manual reference', manufacturerHelp: 'Record the manual or maintenance schedule used for these intervals.',
  baselineDate: 'Baseline service date', baselineHours: 'Baseline running hours', baselineHelp: 'Enter the last verified completion or commissioning baseline. Unclassified old records do not reset these tasks.', intervalHelp: 'Configure at least one interval and its matching baseline. Do not invent a manufacturer interval.', taskValidation: 'Enter at least one positive interval and its matching baseline.',
  configuration_required: 'Configuration required', overdue: 'Overdue', due_soon: 'Due soon', scheduled: 'Scheduled', compliant: 'On schedule', open: 'Open', awaiting_verification: 'Awaiting verification', resolved: 'Verified / resolved', work_recorded: 'Work recorded',
  dueAt: 'Due at', remaining: 'Remaining', daysUnit: 'days', hoursUnit: 'hours', estimateDue: 'Estimated date from recent usage', lastCompleted: 'Last completed', noTasks: 'No service tasks configured. Add tasks from the manufacturer’s schedule to enable preventive reminders.',
  recordSelectedService: 'Record completed tasks', selectedTasks: 'Completed tasks', taskCompletionHelp: 'Select only the tasks actually completed. Their next deadlines will be calculated from this service.', completionChecklist: 'I confirm the selected tasks were completed and checked.', selectTaskRequired: 'Select at least one completed task.', serviceSavedNew: 'Service recorded. Only selected task schedules were updated.',
  findings: 'Early warnings and condition findings', noFindings: 'No open findings in the available data.', workAction: 'Record work performed', verifyInspection: 'Verify inspection', workNote: 'Work completed / verification evidence', workHelp: 'Record the engineer’s action. Sensor findings remain awaiting verification until suitable healthy follow-up readings are available.', verifyHelp: 'Confirm the inspection and record evidence of satisfactory condition.', verifyChecklist: 'Inspection completed and satisfactory condition confirmed.', findingSaved: 'Work recorded. The finding status has been updated.', findingHistory: 'Finding history', detectedAt: 'First detected', lastDetected: 'Last observed', verification: 'Verification', sensor: 'Healthy follow-up readings', inspection: 'Engineer inspection', legacyRecord: 'Legacy / unclassified service', limitations: 'Data notes and limitations', actions: 'Actions',
  oil: 'Engine oil', oil_filter: 'Oil filter', fuel_filter: 'Fuel filter', air_filter: 'Air filter', coolant: 'Coolant', battery: 'Battery', belts: 'Belts', hoses: 'Hoses', custom: 'Custom task',
  fuelLitres: 'Fuel consumed', energyKwhNew: 'Electrical energy', runHoursNew: 'Operating hours', litresPerHour: 'Average fuel rate', kwhPerLitre: 'Fuel productivity', litresPerKwh: 'Specific fuel consumption', averageOutput: 'Average output', conversionEfficiency: 'Electrical conversion efficiency', matchedCoverage: 'Matched measurement coverage',
  litresUnit: 'L', litresHourUnit: 'L/h', litresKwhUnit: 'L/kWh', kwhLitreUnit: 'kWh/L', measured: 'Measured', estimated: 'Estimated', source: 'Measurement source', counter: 'Cumulative fuel counter', flow: 'Fuel-flow measurement', tank: 'Calibrated tank estimate', mixed: 'Mixed sources',
  fuelHelp: 'Consumption is calculated from valid measurements. Communication gaps and counter resets are disclosed below.', efficiencyHelp: 'Electrical energy and fuel are matched over the same intervals. Unloaded consumption remains part of period efficiency.', lhvHelp: 'Percentage efficiency requires the fuel lower heating value (kWh/L) in generator settings.',
  dailyTrend: 'Daily trend', dailyMeasurements: 'Daily measurements', generatorBreakdown: 'Generator breakdown', loadBands: 'Performance by load range', loadBand: 'Load range', previousPeriod: 'Compared with the preceding period', noComparison: 'Insufficient comparable data for the preceding period.', comparisonFuel: 'Fuel consumption change', comparisonEfficiency: 'Specific fuel consumption change', lowerBetter: 'Lower L/kWh indicates better fuel performance.', higherBetter: 'Higher kWh/L indicates better fuel performance.',
  reportTimezone: 'Report timezone', unavailableNote: 'A dash means unavailable, not zero.', qualityNotes: 'Measurement quality', matchedHelp: 'Efficiency includes only intervals with valid fuel and energy measurements.', dateColumn: 'Date',
  analyticsSettings: 'Fuel and condition analysis', engineModel: 'Engine model', nominalFrequency: 'Nominal frequency', nominalBattery: 'Battery system', fuelType: 'Fuel type', diesel: 'Diesel', petrol: 'Petrol', gas: 'Gas', other: 'Other', fuelSource: 'Fuel measurement source', fuelLhv: 'Fuel lower heating value (kWh/L)', optional: 'Optional', tankCapacity: 'Tank capacity (litres)', tankHelp: 'Tank estimates require calibration and recorded fuel additions/transfers; shared tanks cannot identify individual generator use.',
  fuelCurve: 'Manufacturer fuel curve', fuelCurveHelp: 'Optional reference points for healthy operation at known loads.', addPoint: 'Add point', remove: 'Remove', loadPercent: 'Load (%)', curveLitresHour: 'Consumption (L/h)', curveValidation: 'Fuel curve points need distinct load percentages and positive consumption.',
  tankCurve: 'Tank calibration', tankCurveHelp: 'Enter tank level (%) and measured volume (L). Include 0% and 100% calibration points.', levelPercent: 'Level (%)', tankVolume: 'Volume (L)',
  setupSettings: 'Measurement settings can be configured by editing the generator on the dashboard.', noHistory: 'No history recorded.', classifiedTasks: 'Linked service tasks', viewMaintenance: 'View maintenance',
};

const ar = {
  overview: 'نظرة عامة', fuelReport: 'استهلاك الوقود', efficiencyReport: 'كفاءة المولد', reportsIntro: 'تخطيط الصيانة والكشف المبكر عن التغيرات ومتابعة أداء الوقود المقاس.',
  allGenerators: 'جميع المولدات', selectGenerator: 'اختر المولد', customRange: 'تواريخ مخصصة', fromDate: 'من', toDate: 'إلى', refresh: 'تحديث', invalidDates: 'اختر تاريخ بداية ونهاية صالحين.',
  noGenerators: 'أضف مولدًا لبدء إعداد التقارير.', unavailable: 'غير متاح', noData: 'لا تتوفر قياسات صالحة لهذه الفترة.', loadingReport: 'جارٍ تحميل التقرير…', exportReport: 'تصدير التقرير (CSV)',
  period: 'الفترة', recordFuelMovement: 'تسجيل حركة الوقود', movementHelp: 'سجل التعبئة برقم موجب أو التحويل برقم سالب لخزان هذا المولد. لا يمكن نسب استهلاك الخزان المشترك لمولد محدد.', movementDate: 'وقت الحركة', movementLitres: 'اللترات (+ تعبئة / − تحويل)',
  maintenanceDueBanner: '{{overdue}} مهام صيانة متأخرة · {{soon}} تستحق قريبًا',
  maintenanceCompliance: 'الالتزام بالصيانة', monitoredCondition: 'الحالة المراقبة', dataCoverage: 'تغطية البيانات', complianceHelp: 'مهام الصيانة المهيأة التي لم تتجاوز موعدها.', conditionHelp: 'حالة التشغيل المرصودة؛ وليست شهادة بالسلامة الفعلية للمولد.', coverageHelp: 'القراءات القابلة للاستخدام ضمن السجل المحدد.',
  healthy: 'لم يُكتشف خلل مستمر', attention: 'تتطلب الاهتمام', critical: 'تتطلب اهتمامًا عاجلًا', insufficient_data: 'بيانات غير كافية',
  taskSchedules: 'جدول الصيانة الوقائية', taskScheduleHelp: 'استخدم فترات الشركة المصنعة للمحرك. يحين الموعد بحسب ساعات التشغيل أو المدة الزمنية، أيهما أسبق.', addTask: 'إضافة مهمة صيانة', editTask: 'تعديل المهمة', archiveTask: 'أرشفة المهمة', archiveConfirm: 'هل تريد أرشفة مهمة الصيانة؟ سيُحتفظ بسجل الإنجاز.',
  maintenanceDateScope: 'تحدد التواريخ القراءات وسجل النتائج والصيانة المكتملة. تبقى مواعيد المهام والنتائج المفتوحة بحسب الحالة الحالية.',
  taskName: 'اسم المهمة', component: 'المكوّن', intervalHours: 'الفاصل (ساعات تشغيل)', intervalDays: 'الفاصل (أيام)', manufacturerReference: 'مرجع الشركة المصنعة / الدليل', manufacturerHelp: 'سجّل الدليل أو جدول الصيانة المستخدم لتحديد الفترات.',
  baselineDate: 'تاريخ الصيانة المرجعي', baselineHours: 'ساعات التشغيل المرجعية', baselineHelp: 'أدخل آخر إنجاز مؤكد أو بيانات بدء الخدمة. السجلات القديمة غير المصنفة لا تعيد ضبط هذه المهام.', intervalHelp: 'حدد فاصلًا واحدًا على الأقل وبياناته المرجعية. اعتمد فترات الشركة المصنعة.', taskValidation: 'أدخل فاصلًا موجبًا واحدًا على الأقل مع بياناته المرجعية.',
  configuration_required: 'تحتاج إلى إعداد', overdue: 'متأخرة', due_soon: 'مستحقة قريبًا', scheduled: 'مجدولة', compliant: 'ضمن الموعد', open: 'مفتوحة', awaiting_verification: 'بانتظار التحقق', resolved: 'تم التحقق / أُغلقت', work_recorded: 'تم تسجيل العمل',
  dueAt: 'موعد الاستحقاق', remaining: 'المتبقي', daysUnit: 'يوم', hoursUnit: 'ساعة', estimateDue: 'التاريخ التقديري بحسب الاستخدام الأخير', lastCompleted: 'آخر إنجاز', noTasks: 'لم تُضبط مهام الصيانة. أضف مهام من جدول الشركة المصنعة لتفعيل التذكيرات الوقائية.',
  recordSelectedService: 'تسجيل المهام المنجزة', selectedTasks: 'المهام المنجزة', taskCompletionHelp: 'اختر المهام التي أُنجزت بالفعل فقط. تُحسب مواعيدها التالية انطلاقًا من هذه الصيانة.', completionChecklist: 'أؤكد إنجاز المهام المختارة وفحصها.', selectTaskRequired: 'اختر مهمة منجزة واحدة على الأقل.', serviceSavedNew: 'تم تسجيل الصيانة وتحديث مواعيد المهام المختارة فقط.',
  findings: 'التحذيرات المبكرة ونتائج مراقبة الحالة', noFindings: 'لا توجد نتائج مفتوحة في البيانات المتاحة.', workAction: 'تسجيل العمل المنفذ', verifyInspection: 'التحقق من الفحص', workNote: 'العمل المنجز / دليل التحقق', workHelp: 'سجّل إجراء المهندس. تبقى نتائج الحساسات بانتظار التحقق حتى تتوفر قراءات متابعة سليمة ومناسبة.', verifyHelp: 'أكد إجراء الفحص وسجّل ما يثبت سلامة الحالة.', verifyChecklist: 'أُنجز الفحص وتم التأكد من سلامة الحالة.', findingSaved: 'تم تسجيل العمل وتحديث حالة النتيجة.', findingHistory: 'سجل النتائج', detectedAt: 'أول اكتشاف', lastDetected: 'آخر رصد', verification: 'التحقق', sensor: 'قراءات متابعة سليمة', inspection: 'فحص المهندس', legacyRecord: 'صيانة قديمة / غير مصنفة', limitations: 'ملاحظات البيانات وحدود التحليل', actions: 'الإجراءات',
  oil: 'زيت المحرك', oil_filter: 'فلتر الزيت', fuel_filter: 'فلتر الوقود', air_filter: 'فلتر الهواء', coolant: 'سائل التبريد', battery: 'البطارية', belts: 'السيور', hoses: 'الخراطيم', custom: 'مهمة مخصصة',
  fuelLitres: 'الوقود المستهلك', energyKwhNew: 'الطاقة الكهربائية', runHoursNew: 'ساعات التشغيل', litresPerHour: 'متوسط معدل الاستهلاك', kwhPerLitre: 'إنتاجية الوقود', litresPerKwh: 'الاستهلاك النوعي للوقود', averageOutput: 'متوسط القدرة', conversionEfficiency: 'كفاءة التحويل الكهربائي', matchedCoverage: 'تغطية القياسات المتطابقة',
  litresUnit: 'لتر', litresHourUnit: 'لتر/ساعة', litresKwhUnit: 'لتر/ك.و.س', kwhLitreUnit: 'ك.و.س/لتر', measured: 'مقاس', estimated: 'تقديري', source: 'مصدر القياس', counter: 'عداد الوقود التراكمي', flow: 'قياس تدفق الوقود', tank: 'تقدير خزان مُعاير', mixed: 'مصادر متعددة',
  fuelHelp: 'يُحسب الاستهلاك من القياسات الصالحة. تظهر انقطاعات الاتصال وإعادة ضبط العدادات أدناه.', efficiencyHelp: 'تُطابق الطاقة الكهربائية والوقود في الفترات نفسها. يشمل أداء الفترة الوقود المستهلك دون حمل.', lhvHelp: 'تتطلب الكفاءة المئوية تحديد القيمة الحرارية الدنيا للوقود (ك.و.س/لتر) في إعدادات المولد.',
  dailyTrend: 'الاتجاه اليومي', dailyMeasurements: 'القياسات اليومية', generatorBreakdown: 'تفاصيل المولدات', loadBands: 'الأداء بحسب نطاق الحمل', loadBand: 'نطاق الحمل', previousPeriod: 'المقارنة بالفترة السابقة', noComparison: 'لا تتوفر بيانات قابلة للمقارنة مع الفترة السابقة.', comparisonFuel: 'تغير استهلاك الوقود', comparisonEfficiency: 'تغير الاستهلاك النوعي للوقود', lowerBetter: 'انخفاض لتر/ك.و.س يدل على تحسن أداء الوقود.', higherBetter: 'ارتفاع ك.و.س/لتر يدل على تحسن أداء الوقود.',
  reportTimezone: 'المنطقة الزمنية للتقرير', unavailableNote: 'تعني الشرطة أن القيمة غير متاحة، وليست صفرًا.', qualityNotes: 'جودة القياسات', matchedHelp: 'تُحسب الكفاءة فقط للفترات التي تتوفر فيها قياسات وقود وطاقة صالحة.', dateColumn: 'التاريخ',
  analyticsSettings: 'تحليل الوقود وحالة المولد', engineModel: 'طراز المحرك', nominalFrequency: 'التردد الاسمي', nominalBattery: 'نظام البطارية', fuelType: 'نوع الوقود', diesel: 'ديزل', petrol: 'بنزين', gas: 'غاز', other: 'آخر', fuelSource: 'مصدر قياس الوقود', fuelLhv: 'القيمة الحرارية الدنيا للوقود (ك.و.س/لتر)', optional: 'اختياري', tankCapacity: 'سعة الخزان (لتر)', tankHelp: 'تتطلب تقديرات الخزان معايرة وتسجيل الإضافات والتحويلات؛ لا يمكن تحديد استهلاك كل مولد من خزان مشترك.',
  fuelCurve: 'منحنى وقود الشركة المصنعة', fuelCurveHelp: 'نقاط مرجعية اختيارية للتشغيل السليم عند أحمال معروفة.', addPoint: 'إضافة نقطة', remove: 'إزالة', loadPercent: 'الحمل (%)', curveLitresHour: 'الاستهلاك (لتر/ساعة)', curveValidation: 'تتطلب نقاط منحنى الوقود نسب حمل مختلفة واستهلاكًا موجبًا.',
  tankCurve: 'معايرة الخزان', tankCurveHelp: 'أدخل مستوى الخزان (%) والحجم المقاس (لتر). أضف نقطتي معايرة 0% و100%.', levelPercent: 'المستوى (%)', tankVolume: 'الحجم (لتر)',
  setupSettings: 'يمكن ضبط إعدادات القياسات من خلال تعديل المولد في لوحة المتابعة.', noHistory: 'لا يوجد سجل حتى الآن.', classifiedTasks: 'مهام الصيانة المرتبطة', viewMaintenance: 'عرض الصيانة',
};

export function useReportLocale() {
  const context = useLocale();
  return { ...context, t: (key, variables = {}) => {
    const value = (context.locale === 'ar' ? ar : en)[key];
    if (value === undefined) return context.t(key, variables);
    return Object.entries(variables).reduce((text, [name, replacement]) => text.replaceAll(`{{${name}}}`, String(replacement)), value);
  } };
}
