"""add maintenance_mode, rotation_order, and schedule_exceptions

Revision ID: 4b74ade2cfd9
Revises: 55d107be0e11
Create Date: 2026-09-05 13:09:33.373506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b74ade2cfd9'
down_revision: Union[str, None] = '55d107be0e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False, comment='The specific date this exception applies to'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='If True, forces the generator ON during the times below. If False, forces it OFF for the entire day (holiday).'),
    sa.Column('start_time', sa.String(length=5), nullable=True, comment='HH:MM in site-local time (required if is_active=True)'),
    sa.Column('end_time', sa.String(length=5), nullable=True, comment='HH:MM in site-local time (required if is_active=True)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_exceptions_panel_id'), 'schedule_exceptions', ['panel_id'], unique=False)
    op.create_index(op.f('ix_schedule_exceptions_site_id'), 'schedule_exceptions', ['site_id'], unique=False)
    op.add_column('panels', sa.Column('lead_rotation_order', sa.Integer(), nullable=False, comment='Order of preference for being the lead generator (lower = more preferred)'))
    op.add_column('panels', sa.Column('maintenance_mode', sa.Boolean(), nullable=False, comment='If True, panel is skipped in rotation and backup selection'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'maintenance_mode')
    op.drop_column('panels', 'lead_rotation_order')
    op.drop_index(op.f('ix_schedule_exceptions_site_id'), table_name='schedule_exceptions')
    op.drop_index(op.f('ix_schedule_exceptions_panel_id'), table_name='schedule_exceptions')
    op.drop_table('schedule_exceptions')
    # ### end Alembic commands ###
