"""Initial schema

Revision ID: 55d107be0e11
Revises: 
Create Date: 2026-09-05 12:31:16.236784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d107be0e11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('max_parallel_units', sa.Integer(), nullable=True, comment='Optional cap on how many generators can run simultaneously'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('transport_type', sa.String(length=10), nullable=False, comment="'tcp' or 'rtu'"),
    sa.Column('address', sa.String(length=200), nullable=False, comment='IP:port for TCP, serial port path for RTU'),
    sa.Column('unit_id', sa.Integer(), nullable=False, comment='Modbus unit/slave ID'),
    sa.Column('rated_kw', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rated_kvar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Lower value = higher backup priority'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panels_site_id'), 'panels', ['site_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='customer | technician'),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='command_sent | alarm_active | alarm_cleared | status_change | override | system'),
    sa.Column('command', sa.String(length=50), nullable=True, comment='remote_start | remote_stop | set_power | etc.'),
    sa.Column('value', sa.String(length=200), nullable=True, comment='Command value or status detail as string'),
    sa.Column('triggered_by', sa.String(length=50), nullable=False, comment='schedule | threshold | manual | override | system'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Human-readable explanation of why this action was taken'),
    sa.Column('previous_state', sa.String(length=50), nullable=True, comment='Engine status before the command was sent'),
    sa.Column('new_state', sa.String(length=50), nullable=True, comment='Target engine status after the command'),
    sa.Column('load_kw_at_decision', sa.Float(), nullable=True, comment='Fleet or generator load at the time of the decision'),
    sa.Column('capacity_pct_at_decision', sa.Float(), nullable=True, comment='Fleet capacity percentage at the time of the decision'),
    sa.Column('command_result', sa.String(length=50), nullable=True, comment='success | failed | timeout | cooldown_blocked'),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_panel_id'), 'events', ['panel_id'], unique=False)
    op.create_index(op.f('ix_events_site_id'), 'events', ['site_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('override_type', sa.String(length=20), nullable=False, comment='force_start | force_stop'),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True, comment='Optional note from the technician'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overrides_panel_id'), 'overrides', ['panel_id'], unique=False)
    op.create_index(op.f('ix_overrides_site_id'), 'overrides', ['site_id'], unique=False)
    op.create_table('power_setpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('target_kw_pct', sa.Numeric(precision=5, scale=2), nullable=False, comment='Fixed-power kW target as % of rated'),
    sa.Column('target_kvar_pct', sa.Numeric(precision=5, scale=2), nullable=False, comment='Fixed reactive power kVAr target as % of rated'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_power_setpoints_panel_id'), 'power_setpoints', ['panel_id'], unique=True)
    op.create_index(op.f('ix_power_setpoints_site_id'), 'power_setpoints', ['site_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri, 5=Sat, 6=Sun'),
    sa.Column('start_time', sa.String(length=5), nullable=False, comment='HH:MM in site-local time'),
    sa.Column('end_time', sa.String(length=5), nullable=False, comment='HH:MM in site-local time'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_panel_id'), 'schedules', ['panel_id'], unique=False)
    op.create_index(op.f('ix_schedules_site_id'), 'schedules', ['site_id'], unique=False)
    op.create_table('thresholds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=True),
    sa.Column('start_pct', sa.Numeric(precision=5, scale=2), nullable=False, comment='Start backup when site load exceeds this %'),
    sa.Column('stop_pct', sa.Numeric(precision=5, scale=2), nullable=False, comment='Stop backup when site load drops below this %'),
    sa.Column('dwell_seconds', sa.Integer(), nullable=False, comment='Min seconds backup runs before auto-stop is allowed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thresholds_site_id'), 'thresholds', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thresholds_site_id'), table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_index(op.f('ix_schedules_site_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_panel_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_power_setpoints_site_id'), table_name='power_setpoints')
    op.drop_index(op.f('ix_power_setpoints_panel_id'), table_name='power_setpoints')
    op.drop_table('power_setpoints')
    op.drop_index(op.f('ix_overrides_site_id'), table_name='overrides')
    op.drop_index(op.f('ix_overrides_panel_id'), table_name='overrides')
    op.drop_table('overrides')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_site_id'), table_name='events')
    op.drop_index(op.f('ix_events_panel_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_panels_site_id'), table_name='panels')
    op.drop_table('panels')
    op.drop_table('sites')
    # ### end Alembic commands ###
