"""Add daily priorities

Revision ID: f630909bf7ce
Revises: 4b74ade2cfd9
Create Date: 2026-09-06 09:35:02.586169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f630909bf7ce'
down_revision: Union[str, None] = '4b74ade2cfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_priorities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri, 5=Sat, 6=Sun'),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_priorities_panel_id'), 'daily_priorities', ['panel_id'], unique=False)
    op.create_index(op.f('ix_daily_priorities_site_id'), 'daily_priorities', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_priorities_site_id'), table_name='daily_priorities')
    op.drop_index(op.f('ix_daily_priorities_panel_id'), table_name='daily_priorities')
    op.drop_table('daily_priorities')
    # ### end Alembic commands ###
