import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const en = {
  generators: 'Generators', schedule: 'Duty Schedule', rules: 'Rules & Thresholds', reports: 'Reports & Work Logs', diagnostics: 'Diagnostics', overrides: 'Overrides', audit: 'Audit Log', newSite: 'New Site', signOut: 'Sign out', language: 'Change language', switchToDark: 'Switch to dark mode', switchToLight: 'Switch to light mode',
  startingPortal: 'Starting portal…', signInSubtitle: 'Sign in to access your facility power management portal', email: 'Email', password: 'Password', signingIn: 'Signing in…', signIn: 'Sign in', loginFailed: 'Login failed',
  addFacilityTitle: 'Add New Facility Site', editSite: 'Edit Facility Site', newFacility: 'New Facility Site', siteName: 'Site / Facility Name', physicalAddress: 'Physical Address', siteTimezone: 'Site Timezone', maxUnits: 'Max Simultaneous Units (Optional Cap)', cancel: 'Cancel', saving: 'Saving…', saveChanges: 'Save Changes', createSite: 'Create Site', close: 'Close',
  editGenerator: 'Edit Generator', addGenerator: 'Add Generator', controllerModel: 'Controller Model', maintenanceLimits: 'Maintenance warning limits', coolantHigh: 'Coolant high (°C)', oilLow: 'Oil pressure low (bar)', fuelLow: 'Fuel low (%)', batteryLow: 'Battery low (V)', serviceInterval: 'Routine Service Interval (running hours)', generatorName: 'Generator Label / Name', transportProtocol: 'Transport Protocol', slaveId: 'Modbus Slave ID', tcpAddress: 'IP Address & Port (host:port)', serialAddress: 'Serial Port Device Path', ratedPower: 'Rated Active Power (kW)', ratedReactive: 'Rated Reactive Power (kVAr)', tcpOption: 'Modbus TCP (Ethernet)', rtuOption: 'Modbus RTU (RS485 Serial)',
  gatewayOffline: 'Gateway Offline', gatewayOfflineText: 'Live status is disconnected. Controller safety and engine protections continue independently on-site.', manualOverrideActive: 'Manual Override Active', overrideBanner: 'The automated weekly schedule is currently bypassed for {{count}} generator(s).', viewOverrides: 'View Overrides',
  capacity: '{{value}} kW capacity', onDutyToday: 'On duty today', runTime: 'Run time', hoursShort: 'hrs', moreReadings: 'More generator readings', notAvailable: 'Not available', breaker: 'Breaker', closed: 'Closed', open: 'Open', synchronization: 'Synchronization', synchronized: 'Synchronized', notSynchronized: 'Not synchronized', startUnit: 'Start Unit', stopUnit: 'Stop Unit', edit: 'Edit', delete: 'Delete', editGeneratorSettings: 'Edit generator settings', decommissionGenerator: 'Decommission generator', decommissionConfirm: 'Are you sure you want to decommission {{name}}?', weeklyDuty: 'Weekly Duty', onDuty: 'On Duty', standby: 'Standby', today: 'Today', load: 'Load',
  fuelLevel: 'Fuel level', coolantTemperature: 'Coolant temperature', oilPressure: 'Oil pressure', batteryVoltage: 'Battery voltage', engineSpeed: 'Engine speed', frequency: 'Frequency', apparentPower: 'Apparent power', reactivePower: 'Reactive power', reactiveLoad: 'Reactive load', l1Voltage: 'L1-N voltage', l2Voltage: 'L2-N voltage', l3Voltage: 'L3-N voltage', energyProduced: 'Energy produced', startCount: 'Start count', generatorState: 'Generator state',
  unknown: 'Unknown', unreachable: 'Unreachable', alarm: 'Alarm', running: 'Running', stopped: 'Stopped', starting: 'Starting', stopping: 'Stopping', idle: 'Idle', connected: 'Connected', never: 'Never', fault: 'Fault', warning: 'Warning', critical: 'Critical', manual: 'Manual', automatic: 'Automatic', customer: 'Customer', system: 'System', dispatcher: 'Automatic dispatcher', command_sent: 'Command Sent', alarm_active: 'Alarm Active', alarm_cleared: 'Alarm Cleared', force_start: 'Force Start', force_stop: 'Force Stop', remote_start: 'Remote Start', remote_stop: 'Remote Stop', confirmed: 'Confirmed', acknowledged: 'Acknowledged', queued: 'Queued', failed: 'Failed', rejected: 'Rejected', success: 'Success',
  generatorFleet: 'Generator Fleet', fleetSummary: '{{running}} of {{total}} generators active · Total output: {{output}} kW of {{capacity}} kW', loadingGenerators: 'Loading generator status…', noGenerators: 'No generators configured for this facility site yet.', addFirstGenerator: 'Add First Generator', startSent: 'Start command sent', stopSent: 'Stop command sent', generatorDeleted: 'Generator decommissioned successfully.', siteSwitchFailed: 'Failed to switch site: {{message}}',
  scheduleSubtitle: 'Choose which generators are on primary duty throughout the week · Facility Timezone:', saveSchedule: 'Save Schedule', scheduleSaved: 'Schedule saved and synchronized with the controller.', quickPresets: 'Quick Schedule Presets', dailyRotation: 'Daily Rotation', loadFollowing: 'Load-Following Only', manualNoSchedule: 'Manual (No Schedule)', presetApplied: 'Applied “{{name}}” preset.', noRestWarning: '{{name}} is scheduled 7 days a week with no rest days.', generator: 'Generator', on: 'ON', off: 'off', startTime: 'Start Time', endTime: 'End Time',
  settings: 'Settings', settingsSubtitle: 'Configure site properties and load management rules', loadingSettings: 'Loading settings…', facilityDetails: 'Facility Site Details', facilityDetailsText: 'Manage the core details for this installation.', editDetails: 'Edit Details', timezone: 'Timezone', addressLocation: 'Address / Location', notSpecified: 'Not specified', loadRules: 'Load Management Rules', loadRulesText: 'Configure automated backup assistance when facility power demand rises.', minRunDuration: 'Minimum run duration before releasing backup', minute: '{{count}} minute', minutes: '{{count}} minutes', recommended: 'recommended', dwellHelp: 'Ensures the backup engine reaches stable operating temperature before being shut down.', saveRules: 'Save Rules', startThresholds: 'Backup Start Thresholds', startThresholdsText: 'Set the total facility load percentage at which each backup generator should be started. The first backup, with the lowest priority number, is started first.', saveStartRules: 'Save Start Rules', releaseThresholds: 'Backup Release Thresholds', releaseThresholdsText: 'Set the total facility load percentage at which each backup generator should be stopped. The last backup started, with the highest priority number, is released first.', saveReleaseRules: 'Save Release Rules', dailyBackupOrder: 'Daily Backup Order', dailyBackupOrderText: 'Set backup generator rotation priority for each day.', savePriorities: 'Save Priorities', dangerZone: 'Danger Zone', dangerText: 'Deleting a site permanently erases all its generators, schedules, and historical data.', deleteSite: 'Delete Site', deleteSiteConfirm: 'Are you sure you want to permanently delete “{{name}}” and all its generators? This cannot be undone.', siteDeleted: 'Site deleted successfully. You will be signed out to reset your session.', siteUpdated: 'Site details updated successfully.', thresholdsSaved: 'Load management thresholds updated successfully.', prioritiesSaved: 'Daily backup priorities saved.', startRulesSaved: 'Backup start thresholds saved.', releaseRulesSaved: 'Backup release thresholds saved.', duplicatePriority: 'Duplicate priority detected on {{day}}. Each generator must have a unique priority from 1 to {{count}}.', invalidPriority: 'Priority {{priority}} on {{day}} exceeds the number of generators at this site ({{count}}).', thresholdValidation: 'The stop threshold must be lower than the start threshold to prevent rapid engine cycling.', generatorShort: 'Gen {{number}}',
  reportsTitle: 'Generator Work & Operations Reports', reportsSubtitle: 'Operating run times, energy output, start cycles, and duty records', sevenDays: '7 Days', thirtyDays: '30 Days', allTime: 'All Time', generating: 'Generating…', exportCsv: 'Export Report (CSV)', exportFailed: 'Failed to generate CSV export', maintenanceExportFailed: 'Failed to export the maintenance report', fleetHours: 'Fleet Operating Hours', energyDelivered: 'Energy Delivered', startCycles: 'Start Cycles', starts: 'starts', fleetAvailability: 'Fleet Availability', utilizationBreakdown: 'Generator Work & Utilization Breakdown', generatorUnit: 'Generator Unit', capacityLabel: 'Capacity', runState: 'Run State', operatingHours: 'Operating Hours', energyKwh: 'Energy (kWh)', avgLoad: 'Avg Load %', peakLoad: 'Peak Load %', faults: 'Faults', maintenance: 'Maintenance', analyzing: 'Analyzing…', viewReport: 'View report', preventiveMaintenance: 'Preventive Maintenance', basedOnReadings: 'Based on {{count}} stored readings for {{period}}', recordService: 'Record completed service', exportThisReport: 'Export this report', conditionScore: 'Condition score / 100', nextService: 'Next routine service at {{next}} hours · {{remaining}} hours remaining', noWarning: 'No configured condition warning was detected in the available readings.', recommendedAction: 'Recommended:', recentEvents: 'Recent Duty & Work Events ({{period}})', timestampUtc: 'Timestamp (UTC)', unit: 'Unit', action: 'Action', commandStatus: 'Command / Status', triggerSource: 'Trigger Source', reason: 'Reason', noEventsPeriod: 'No events recorded in this period.', serviceDatePrompt: 'Service date (YYYY-MM-DD)', serviceHoursPrompt: 'Generator running hours at service', serviceByPrompt: 'Service performed by (optional)', serviceNotesPrompt: 'Work completed / notes (optional)', routineService: 'Routine service', recordCompletedService: 'Record completed service', serviceFormHelp: 'Enter the service details below. The current controller run hours are filled automatically.', serviceDate: 'Service date', runningHoursAtService: 'Running hours at service', runningHours: 'Running hours', serviceType: 'Service type', performedBy: 'Performed by', performedByPlaceholder: 'Technician or service company', serviceNotes: 'Work completed / notes', serviceNotesPlaceholder: 'Parts replaced, inspections, measurements, and follow-up work', saveService: 'Save service record', savingService: 'Saving service…', serviceSaved: 'Completed service recorded successfully.', serviceValidationError: 'Enter a valid service date, service type, and non-negative running hours.', completedServiceHistory: 'Completed service history', completedServiceCount: '{{count}} recorded service(s)', noCompletedServices: 'No completed services have been recorded for this generator.', exportServiceHistory: 'Export service history (CSV)', serviceExportFailed: 'Failed to export completed service history',
  clearMaintenanceAlarms: 'Clear maintenance alarms', confirmAlarmClear: 'Confirm that the alarms have been resolved', alarmClearHelp: 'This closes the alarms in the maintenance analysis and records the engineer’s note in the audit log. It does not reset a fault still reported by the physical controller.', alarmResolutionNote: 'Engineer resolution note', alarmResolutionPlaceholder: 'Describe the checks, repairs, tests, and final condition', alarmClearReasonRequired: 'Enter a resolution note of at least 3 characters.', confirmClearAlarms: 'Clear resolved alarms', clearingMaintenanceAlarms: 'Clearing alarms…', alarmsClearedSuccess: '{{count}} resolved alarm(s) cleared from the maintenance report.',
  markFindingResolved: 'Mark resolved', confirmFindingResolved: 'Confirm this finding was checked and resolved', findingResolutionHelp: 'The engineer’s note is retained in the audit log. The condition score is recalculated from findings that remain unresolved.', confirmFindingClear: 'Resolve this finding', findingClearedSuccess: 'The finding was resolved and the generator health score was recalculated.',
  diagnosticsTitle: 'Diagnostic Telemetry', diagnosticsSubtitle: 'Raw register memory and Modbus connection diagnostics', readingRegisters: 'Reading registers…', pollNow: 'Poll Now', transport: 'Transport', linkHealth: 'Link Health', failures: 'Consecutive Failures', lastPoll: 'Last Successful Poll', registerName: 'Register Name', address: 'Address', type: 'Type', rawValue: 'Raw Value', scaledValue: 'Scaled Engineering Value', description: 'Description',
  overridesTitle: 'Manual Overrides', overridesSubtitle: 'Force generator run states with mandatory expiration safeguards', engageOverride: 'Engage Manual Override', targetGenerator: 'Target Generator', commandedAction: 'Commanded Action', forceStart: 'Force Start (Run Unit)', forceStop: 'Force Stop (Suppress Unit)', expiryDuration: 'Auto-Expiry Duration (Mandatory)', hour: '{{count}} hour', hours: '{{count}} hours', overrideHelp: 'Prevents manual overrides from silently suppressing schedules indefinitely.', auditReason: 'Reason for Audit Log', reasonPlaceholder: 'e.g. Scheduled fuel filter maintenance', engaging: 'Engaging…', activeOverrides: 'Active Overrides ({{count}})', noOverrides: 'No active overrides. All generators are following the automated schedule and load rules.', forceStartLabel: 'FORCE START', forceStopLabel: 'FORCE STOP', expiresAt: 'Expires at:', note: 'Note:', releaseOverride: 'Release Override', overrideIssued: 'Override command issued. Active for {{count}} minutes.', overrideReleased: 'Override released. Panel returned to automated duty.',
  auditTitle: 'Audit Event Log', auditSubtitle: 'Record of all commands, alarms, and automated decisions', refreshing: 'Refreshing…', refreshLog: 'Refresh Log', exportAuditCsv: 'Export CSV', exportingAudit: 'Exporting…', auditExportFailed: 'Failed to export the audit log', clearAuditLog: 'Clear Log', clearingAudit: 'Clearing…', clearAuditConfirm: 'Permanently delete the audit events matching the current filters? This cannot be undone.', filterUnit: 'Filter Unit:', allUnits: 'All Units', eventType: 'Event Type:', allEvents: 'All Events', commandSent: 'Command Sent', alarmActive: 'Alarm Active', alarmCleared: 'Alarm Cleared', override: 'Override', systemAlert: 'System / Alert', timestamp: 'Timestamp', event: 'Event', commandValue: 'Command / Value', triggeredBy: 'Triggered By', loadingEvents: 'Loading events…', noEvents: 'No events recorded.', siteSystem: 'Site / System', ok: 'OK',
  mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun', monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday', friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday',
};

const ar = {
  generators: 'المولدات', schedule: 'جدول التشغيل', rules: 'القواعد والحدود', reports: 'التقارير وسجل العمل', diagnostics: 'التشخيص', overrides: 'التجاوزات', audit: 'سجل التدقيق', newSite: 'موقع جديد', signOut: 'تسجيل الخروج', language: 'تغيير اللغة', switchToDark: 'التبديل إلى الوضع الداكن', switchToLight: 'التبديل إلى الوضع الفاتح',
  startingPortal: 'جارٍ تشغيل البوابة…', signInSubtitle: 'سجّل الدخول للوصول إلى بوابة إدارة الطاقة في منشأتك', email: 'البريد الإلكتروني', password: 'كلمة المرور', signingIn: 'جارٍ تسجيل الدخول…', signIn: 'تسجيل الدخول', loginFailed: 'تعذر تسجيل الدخول',
  addFacilityTitle: 'إضافة موقع منشأة جديد', editSite: 'تعديل موقع المنشأة', newFacility: 'موقع منشأة جديد', siteName: 'اسم الموقع / المنشأة', physicalAddress: 'العنوان الفعلي', siteTimezone: 'المنطقة الزمنية للموقع', maxUnits: 'الحد الأقصى للوحدات المتزامنة (اختياري)', cancel: 'إلغاء', saving: 'جارٍ الحفظ…', saveChanges: 'حفظ التغييرات', createSite: 'إنشاء الموقع', close: 'إغلاق',
  editGenerator: 'تعديل المولد', addGenerator: 'إضافة مولد', controllerModel: 'طراز لوحة التحكم', maintenanceLimits: 'حدود تحذيرات الصيانة', coolantHigh: 'ارتفاع حرارة سائل التبريد (°م)', oilLow: 'انخفاض ضغط الزيت (بار)', fuelLow: 'انخفاض الوقود (%)', batteryLow: 'انخفاض جهد البطارية (فولت)', serviceInterval: 'فاصل الصيانة الدورية (ساعات التشغيل)', generatorName: 'اسم / تسمية المولد', transportProtocol: 'بروتوكول الاتصال', slaveId: 'معرّف وحدة Modbus', tcpAddress: 'عنوان IP والمنفذ (host:port)', serialAddress: 'مسار منفذ الاتصال التسلسلي', ratedPower: 'القدرة الفعالة المقننة (kW)', ratedReactive: 'القدرة غير الفعالة المقننة (kVAr)', tcpOption: 'Modbus TCP (إيثرنت)', rtuOption: 'Modbus RTU (اتصال تسلسلي RS485)',
  gatewayOffline: 'بوابة الاتصال غير متصلة', gatewayOfflineText: 'الاتصال بالحالة اللحظية منقطع. تستمر وسائل حماية وحدة التحكم والمحرك بصورة مستقلة في الموقع.', manualOverrideActive: 'التجاوز اليدوي نشط', overrideBanner: 'تم تجاوز الجدول الأسبوعي الآلي حاليًا لعدد {{count}} من المولدات.', viewOverrides: 'عرض التجاوزات',
  capacity: 'قدرة {{value}} kW', onDutyToday: 'في الخدمة اليوم', runTime: 'وقت التشغيل', hoursShort: 'ساعة', moreReadings: 'المزيد من قراءات المولد', notAvailable: 'غير متاح', breaker: 'القاطع', closed: 'مغلق', open: 'مفتوح', synchronization: 'المزامنة', synchronized: 'متزامن', notSynchronized: 'غير متزامن', startUnit: 'تشغيل الوحدة', stopUnit: 'إيقاف الوحدة', edit: 'تعديل', delete: 'حذف', editGeneratorSettings: 'تعديل إعدادات المولد', decommissionGenerator: 'إخراج المولد من الخدمة', decommissionConfirm: 'هل تريد بالتأكيد إخراج {{name}} من الخدمة؟', weeklyDuty: 'المناوبة الأسبوعية', onDuty: 'في الخدمة', standby: 'احتياطي', today: 'اليوم', load: 'الحمل',
  fuelLevel: 'مستوى الوقود', coolantTemperature: 'حرارة سائل التبريد', oilPressure: 'ضغط الزيت', batteryVoltage: 'جهد البطارية', engineSpeed: 'سرعة المحرك', frequency: 'التردد', apparentPower: 'القدرة الظاهرية', reactivePower: 'القدرة غير الفعالة', reactiveLoad: 'الحمل غير الفعال', l1Voltage: 'جهد L1-N', l2Voltage: 'جهد L2-N', l3Voltage: 'جهد L3-N', energyProduced: 'الطاقة المنتجة', startCount: 'عدد مرات التشغيل', generatorState: 'حالة المولد',
  unknown: 'غير معروف', unreachable: 'يتعذر الوصول', alarm: 'إنذار', running: 'يعمل', stopped: 'متوقف', starting: 'قيد التشغيل', stopping: 'قيد الإيقاف', idle: 'خامل', connected: 'متصل', never: 'أبدًا', fault: 'عطل', warning: 'تحذير', critical: 'حرج', manual: 'يدوي', automatic: 'آلي', customer: 'العميل', system: 'النظام', dispatcher: 'موزع الأحمال الآلي', command_sent: 'تم إرسال أمر', alarm_active: 'إنذار نشط', alarm_cleared: 'تم مسح الإنذار', force_start: 'فرض التشغيل', force_stop: 'فرض الإيقاف', remote_start: 'تشغيل عن بُعد', remote_stop: 'إيقاف عن بُعد', confirmed: 'مؤكد', acknowledged: 'تم الاستلام', queued: 'في قائمة الانتظار', failed: 'فشل', rejected: 'مرفوض', success: 'نجاح',
  generatorFleet: 'أسطول المولدات', fleetSummary: '{{running}} من أصل {{total}} مولدات تعمل · إجمالي الخرج: {{output}} kW من {{capacity}} kW', loadingGenerators: 'جارٍ تحميل حالة المولدات…', noGenerators: 'لا توجد مولدات مهيأة لهذا الموقع حتى الآن.', addFirstGenerator: 'إضافة أول مولد', startSent: 'تم إرسال أمر التشغيل', stopSent: 'تم إرسال أمر الإيقاف', generatorDeleted: 'تم إخراج المولد من الخدمة بنجاح.', siteSwitchFailed: 'تعذر تبديل الموقع: {{message}}',
  scheduleSubtitle: 'اختر المولدات المناوبة الأساسية خلال الأسبوع · المنطقة الزمنية للمنشأة:', saveSchedule: 'حفظ الجدول', scheduleSaved: 'تم حفظ الجدول ومزامنته مع وحدة التحكم.', quickPresets: 'إعدادات الجدول السريعة', dailyRotation: 'تناوب يومي', loadFollowing: 'حسب الحمل فقط', manualNoSchedule: 'يدوي (دون جدول)', presetApplied: 'تم تطبيق الإعداد «{{name}}».', noRestWarning: 'المولد {{name}} مجدول طوال أيام الأسبوع دون أيام راحة.', generator: 'المولد', on: 'تشغيل', off: 'إيقاف', startTime: 'وقت البدء', endTime: 'وقت الانتهاء',
  settings: 'الإعدادات', settingsSubtitle: 'تهيئة خصائص الموقع وقواعد إدارة الأحمال', loadingSettings: 'جارٍ تحميل الإعدادات…', facilityDetails: 'بيانات موقع المنشأة', facilityDetailsText: 'إدارة البيانات الأساسية لهذا التركيب.', editDetails: 'تعديل البيانات', timezone: 'المنطقة الزمنية', addressLocation: 'العنوان / الموقع', notSpecified: 'غير محدد', loadRules: 'قواعد إدارة الأحمال', loadRulesText: 'تهيئة دعم المولدات الاحتياطية تلقائيًا عند ارتفاع طلب المنشأة على الطاقة.', minRunDuration: 'أقل مدة تشغيل قبل فصل المولد الاحتياطي', minute: '{{count}} دقيقة', minutes: '{{count}} دقائق', recommended: 'موصى به', dwellHelp: 'يضمن وصول المحرك الاحتياطي إلى درجة تشغيل مستقرة قبل إيقافه.', saveRules: 'حفظ القواعد', startThresholds: 'حدود تشغيل المولدات الاحتياطية', startThresholdsText: 'حدد نسبة الحمل الكلي للمنشأة التي يبدأ عندها كل مولد احتياطي. يبدأ أولًا المولد ذو رقم الأولوية الأقل.', saveStartRules: 'حفظ قواعد التشغيل', releaseThresholds: 'حدود فصل المولدات الاحتياطية', releaseThresholdsText: 'حدد نسبة الحمل الكلي للمنشأة التي يتوقف عندها كل مولد احتياطي. يُفصل أولًا آخر مولد تم تشغيله، وهو صاحب رقم الأولوية الأعلى.', saveReleaseRules: 'حفظ قواعد الفصل', dailyBackupOrder: 'ترتيب الاحتياط اليومي', dailyBackupOrderText: 'حدد أولوية تناوب المولدات الاحتياطية لكل يوم.', savePriorities: 'حفظ الأولويات', dangerZone: 'منطقة الخطر', dangerText: 'يؤدي حذف الموقع إلى مسح جميع مولداته وجداوله وبياناته التاريخية نهائيًا.', deleteSite: 'حذف الموقع', deleteSiteConfirm: 'هل تريد بالتأكيد حذف «{{name}}» وجميع مولداته نهائيًا؟ لا يمكن التراجع عن ذلك.', siteDeleted: 'تم حذف الموقع بنجاح. سيتم تسجيل خروجك لإعادة ضبط الجلسة.', siteUpdated: 'تم تحديث بيانات الموقع بنجاح.', thresholdsSaved: 'تم تحديث حدود إدارة الأحمال بنجاح.', prioritiesSaved: 'تم حفظ أولويات الاحتياط اليومية.', startRulesSaved: 'تم حفظ حدود تشغيل الاحتياط.', releaseRulesSaved: 'تم حفظ حدود فصل الاحتياط.', duplicatePriority: 'توجد أولوية مكررة يوم {{day}}. يجب أن تكون لكل مولد أولوية فريدة من 1 إلى {{count}}.', invalidPriority: 'الأولوية {{priority}} يوم {{day}} تتجاوز عدد مولدات الموقع ({{count}}).', thresholdValidation: 'يجب أن يكون حد الإيقاف أقل من حد التشغيل لمنع التشغيل والإيقاف السريع للمحرك.', generatorShort: 'مولد {{number}}',
  reportsTitle: 'تقارير عمل وتشغيل المولدات', reportsSubtitle: 'ساعات التشغيل والطاقة المنتجة ودورات البدء وسجلات المناوبة', sevenDays: '7 أيام', thirtyDays: '30 يومًا', allTime: 'كل المدة', generating: 'جارٍ الإنشاء…', exportCsv: 'تصدير التقرير (CSV)', exportFailed: 'تعذر إنشاء ملف التقرير', maintenanceExportFailed: 'تعذر تصدير تقرير الصيانة', fleetHours: 'ساعات تشغيل الأسطول', energyDelivered: 'الطاقة الموردة', startCycles: 'دورات التشغيل', starts: 'عملية تشغيل', fleetAvailability: 'جاهزية الأسطول', utilizationBreakdown: 'تفاصيل عمل المولدات واستخدامها', generatorUnit: 'وحدة المولد', capacityLabel: 'القدرة', runState: 'حالة التشغيل', operatingHours: 'ساعات التشغيل', energyKwh: 'الطاقة (kWh)', avgLoad: 'متوسط الحمل %', peakLoad: 'أقصى الحمل %', faults: 'الأعطال', maintenance: 'الصيانة', analyzing: 'جارٍ التحليل…', viewReport: 'عرض التقرير', preventiveMaintenance: 'الصيانة الوقائية', basedOnReadings: 'استنادًا إلى {{count}} قراءة محفوظة لمدة {{period}}', recordService: 'تسجيل صيانة مكتملة', exportThisReport: 'تصدير هذا التقرير', conditionScore: 'مؤشر الحالة / 100', nextService: 'الصيانة الدورية التالية عند {{next}} ساعة · متبقي {{remaining}} ساعة', noWarning: 'لم يتم اكتشاف أي تحذير حالة مهيأ ضمن القراءات المتاحة.', recommendedAction: 'الإجراء الموصى به:', recentEvents: 'أحداث المناوبة والعمل الأخيرة ({{period}})', timestampUtc: 'الوقت (UTC)', unit: 'الوحدة', action: 'الإجراء', commandStatus: 'الأمر / الحالة', triggerSource: 'مصدر التشغيل', reason: 'السبب', noEventsPeriod: 'لا توجد أحداث مسجلة خلال هذه المدة.', serviceDatePrompt: 'تاريخ الصيانة (YYYY-MM-DD)', serviceHoursPrompt: 'ساعات تشغيل المولد عند الصيانة', serviceByPrompt: 'منفذ الصيانة (اختياري)', serviceNotesPrompt: 'العمل المنجز / الملاحظات (اختياري)', routineService: 'صيانة دورية', recordCompletedService: 'تسجيل صيانة مكتملة', serviceFormHelp: 'أدخل تفاصيل الصيانة أدناه. تُملأ ساعات تشغيل وحدة التحكم الحالية تلقائيًا.', serviceDate: 'تاريخ الصيانة', runningHoursAtService: 'ساعات التشغيل عند الصيانة', runningHours: 'ساعات التشغيل', serviceType: 'نوع الصيانة', performedBy: 'نفذت بواسطة', performedByPlaceholder: 'الفني أو شركة الصيانة', serviceNotes: 'العمل المنجز / الملاحظات', serviceNotesPlaceholder: 'القطع المستبدلة والفحوصات والقياسات وأعمال المتابعة', saveService: 'حفظ سجل الصيانة', savingService: 'جارٍ حفظ الصيانة…', serviceSaved: 'تم تسجيل الصيانة المكتملة بنجاح.', serviceValidationError: 'أدخل تاريخ صيانة ونوع صيانة وساعات تشغيل غير سالبة وصحيحة.', completedServiceHistory: 'سجل الصيانة المكتملة', completedServiceCount: '{{count}} سجل صيانة', noCompletedServices: 'لم يتم تسجيل أي صيانة مكتملة لهذا المولد.', exportServiceHistory: 'تصدير سجل الصيانة (CSV)', serviceExportFailed: 'تعذر تصدير سجل الصيانة المكتملة',
  clearMaintenanceAlarms: 'مسح إنذارات الصيانة', confirmAlarmClear: 'تأكيد معالجة الإنذارات', alarmClearHelp: 'يؤدي هذا إلى إغلاق الإنذارات في تحليل الصيانة وتسجيل ملاحظة المهندس في سجل التدقيق، ولا يعيد ضبط أي عطل ما زالت لوحة التحكم الفعلية تبلغ عنه.', alarmResolutionNote: 'ملاحظة المعالجة من المهندس', alarmResolutionPlaceholder: 'صف الفحوصات والإصلاحات والاختبارات والحالة النهائية', alarmClearReasonRequired: 'أدخل ملاحظة معالجة لا تقل عن 3 أحرف.', confirmClearAlarms: 'مسح الإنذارات المعالجة', clearingMaintenanceAlarms: 'جارٍ مسح الإنذارات…', alarmsClearedSuccess: 'تم مسح {{count}} من الإنذارات المعالجة من تقرير الصيانة.',
  markFindingResolved: 'تحديد كمعالج', confirmFindingResolved: 'تأكيد فحص هذه النتيجة ومعالجتها', findingResolutionHelp: 'تُحفظ ملاحظة المهندس في سجل التدقيق ويُعاد حساب مؤشر حالة المولد من النتائج التي لم تُعالج بعد.', confirmFindingClear: 'معالجة هذه النتيجة', findingClearedSuccess: 'تمت معالجة النتيجة وإعادة حساب مؤشر حالة المولد.',
  diagnosticsTitle: 'بيانات التشخيص', diagnosticsSubtitle: 'ذاكرة السجلات الخام وتشخيص اتصال Modbus', readingRegisters: 'جارٍ قراءة السجلات…', pollNow: 'قراءة الآن', transport: 'وسيلة الاتصال', linkHealth: 'حالة الاتصال', failures: 'الإخفاقات المتتالية', lastPoll: 'آخر قراءة ناجحة', registerName: 'اسم السجل', address: 'العنوان', type: 'النوع', rawValue: 'القيمة الخام', scaledValue: 'القيمة الهندسية المحوّلة', description: 'الوصف',
  overridesTitle: 'التجاوزات اليدوية', overridesSubtitle: 'فرض حالات تشغيل المولد مع مدة انتهاء إلزامية للحماية', engageOverride: 'تفعيل تجاوز يدوي', targetGenerator: 'المولد المستهدف', commandedAction: 'الإجراء المطلوب', forceStart: 'فرض التشغيل (تشغيل الوحدة)', forceStop: 'فرض الإيقاف (تعطيل الوحدة)', expiryDuration: 'مدة الانتهاء التلقائي (إلزامية)', hour: 'ساعة واحدة', hours: '{{count}} ساعات', overrideHelp: 'يمنع التجاوز اليدوي من تعطيل الجداول إلى أجل غير محدد دون تنبيه.', auditReason: 'سبب الإدخال في سجل التدقيق', reasonPlaceholder: 'مثال: صيانة دورية لمرشح الوقود', engaging: 'جارٍ التفعيل…', activeOverrides: 'التجاوزات النشطة ({{count}})', noOverrides: 'لا توجد تجاوزات نشطة. جميع المولدات تتبع الجدول الآلي وقواعد الحمل.', forceStartLabel: 'فرض التشغيل', forceStopLabel: 'فرض الإيقاف', expiresAt: 'ينتهي عند:', note: 'ملاحظة:', releaseOverride: 'إلغاء التجاوز', overrideIssued: 'صدر أمر التجاوز، وسيظل نشطًا لمدة {{count}} دقيقة.', overrideReleased: 'تم إلغاء التجاوز وعادت اللوحة إلى المناوبة الآلية.',
  auditTitle: 'سجل أحداث التدقيق', auditSubtitle: 'سجل لجميع الأوامر والإنذارات والقرارات الآلية', refreshing: 'جارٍ التحديث…', refreshLog: 'تحديث السجل', exportAuditCsv: 'تصدير CSV', exportingAudit: 'جارٍ التصدير…', auditExportFailed: 'تعذر تصدير سجل التدقيق', clearAuditLog: 'مسح السجل', clearingAudit: 'جارٍ المسح…', clearAuditConfirm: 'هل تريد حذف أحداث التدقيق المطابقة لعوامل التصفية الحالية نهائيًا؟ لا يمكن التراجع عن ذلك.', filterUnit: 'تصفية حسب الوحدة:', allUnits: 'كل الوحدات', eventType: 'نوع الحدث:', allEvents: 'كل الأحداث', commandSent: 'تم إرسال أمر', alarmActive: 'إنذار نشط', alarmCleared: 'تم مسح الإنذار', override: 'تجاوز', systemAlert: 'النظام / تنبيه', timestamp: 'الوقت', event: 'الحدث', commandValue: 'الأمر / القيمة', triggeredBy: 'تم بواسطة', loadingEvents: 'جارٍ تحميل الأحداث…', noEvents: 'لا توجد أحداث مسجلة.', siteSystem: 'الموقع / النظام', ok: 'موافق',
  mon: 'اثنين', tue: 'ثلاثاء', wed: 'أربعاء', thu: 'خميس', fri: 'جمعة', sat: 'سبت', sun: 'أحد', monday: 'اثنين', tuesday: 'ثلاثاء', wednesday: 'أربعاء', thursday: 'خميس', friday: 'جمعة', saturday: 'سبت', sunday: 'أحد',
};

const messages = { en, ar };
const arabicServerText = {
  'Attention required': 'تتطلب الحالة اهتمامًا',
  'Plan maintenance': 'خطط للصيانة',
  'No condition warning detected': 'لم يتم اكتشاف تحذير في الحالة',
  'Routine service interval is approaching': 'موعد الصيانة الدورية يقترب',
  'Routine service interval reached': 'حان موعد الصيانة الدورية',
  'Inspect coolant level, radiator airflow, hoses and thermostat before the next loaded run.': 'افحص مستوى سائل التبريد وتدفق هواء المشع والخراطيم ومنظم الحرارة قبل التشغيل التالي تحت الحمل.',
  'Verify oil level and grade, inspect for leaks, and confirm pressure with a calibrated instrument.': 'تحقق من مستوى الزيت ودرجته وافحص التسربات وأكد الضغط باستخدام أداة معايرة.',
  'Inspect terminals and charging system, then load-test the starter battery.': 'افحص أقطاب البطارية ونظام الشحن ثم اختبر بطارية التشغيل تحت الحمل.',
  'Refuel and inspect the tank, transfer pump, filters and level sender.': 'أعد التزود بالوقود وافحص الخزان ومضخة النقل والمرشحات وحساس المستوى.',
  'Check speed control/governor behavior and confirm the configured nominal frequency.': 'افحص سلوك منظم السرعة وتأكد من التردد الاسمي المهيأ.',
  'Review load sharing and capacity; inspect the unit if overload occurred.': 'راجع تقاسم الحمل والقدرة وافحص الوحدة إذا حدث حمل زائد.',
  'Review the alarm history and close out the underlying causes before relying on the unit.': 'راجع سجل الإنذارات وعالج أسبابها الأساسية قبل الاعتماد على الوحدة.',
  'Plan the manufacturer-prescribed service and record completion in the maintenance system.': 'خطط للصيانة المقررة من الشركة المصنعة وسجّل اكتمالها في نظام الصيانة.',
  "This report supports preventive maintenance planning; it does not replace inspection or the engine manufacturer's service schedule.": 'يدعم هذا التقرير تخطيط الصيانة الوقائية ولا يغني عن الفحص أو جدول صيانة المحرك الخاص بالشركة المصنعة.',
  'Accuracy depends on commissioned controller addresses, scaling and sensor calibration.': 'تعتمد الدقة على صحة عناوين وحدة التحكم ومعاملات التحويل ومعايرة الحساسات عند التشغيل.',
};
const arabicMetricNames = {
  'Coolant temperature': 'درجة حرارة سائل التبريد', 'coolant temperature': 'درجة حرارة سائل التبريد',
  'Oil pressure': 'ضغط الزيت', 'oil pressure': 'ضغط الزيت',
  'Starter battery voltage': 'جهد بطارية التشغيل', 'starter battery voltage': 'جهد بطارية التشغيل',
  'Fuel level': 'مستوى الوقود', 'fuel level': 'مستوى الوقود',
  'Generator frequency': 'تردد المولد', 'generator frequency': 'تردد المولد',
  'Generator load': 'حمل المولد', 'generator load': 'حمل المولد',
};
const arabicCodes = {
  preheat: 'تسخين أولي', cranking: 'تدوير المحرك', cooldown: 'تبريد', on_load: 'تحت الحمل', warming_up: 'إحماء', shutting_down: 'قيد الإيقاف',
  emergency_stop: 'إيقاف طارئ', low_oil_pressure: 'انخفاض ضغط الزيت', high_coolant_temp: 'ارتفاع حرارة سائل التبريد', low_coolant_temp: 'انخفاض حرارة سائل التبريد',
  underspeed: 'انخفاض السرعة', overspeed: 'ارتفاع السرعة', generator_over_frequency: 'ارتفاع تردد المولد', generator_under_frequency: 'انخفاض تردد المولد',
  generator_over_voltage: 'ارتفاع جهد المولد', generator_under_voltage: 'انخفاض جهد المولد', battery_over_voltage: 'ارتفاع جهد البطارية', battery_under_voltage: 'انخفاض جهد البطارية',
  overload_alarm: 'إنذار حمل زائد', generator_short_circuit: 'قصر كهربائي في المولد', mains_failure: 'فشل الشبكة', generator_earth_fault: 'تسرب أرضي في المولد',
  fuel_level_low: 'انخفاض مستوى الوقود', fuel_level_high: 'ارتفاع مستوى الوقود', charge_alternator_fail: 'فشل مولد الشحن', fail_to_start: 'فشل التشغيل', fail_to_stop: 'فشل الإيقاف',
  loss_of_speed_signal: 'فقدان إشارة السرعة', low_fuel_pressure: 'انخفاض ضغط الوقود', high_fuel_pressure: 'ارتفاع ضغط الوقود',
};
const LocaleContext = createContext(null);

export function LocaleProvider({ children }) {
  const [locale, setLocale] = useState(() => localStorage.getItem('locale') || 'en');
  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
    localStorage.setItem('locale', locale);
  }, [locale]);

  const value = useMemo(() => {
    const t = (key, variables = {}) => {
      const template = messages[locale]?.[key] ?? en[key] ?? key;
      return Object.entries(variables).reduce((text, [name, replacement]) => text.replaceAll(`{{${name}}}`, String(replacement)), template);
    };
    const languageTag = locale === 'ar' ? 'ar-SA' : 'en-US';
    const translateText = (value) => {
      if (locale !== 'ar' || typeof value !== 'string') return value;
      if (arabicServerText[value]) return arabicServerText[value];
      let match = value.match(/^(.+) requires attention$/);
      if (match) return `${arabicMetricNames[match[1]] || match[1]} يتطلب الاهتمام`;
      match = value.match(/^(Maximum|Minimum) (.+) (reached|was) ([\d.]+) (.+)\.$/);
      if (match) return `${match[1] === 'Maximum' ? 'أقصى' : 'أدنى'} ${arabicMetricNames[match[2]] || match[2]} ${match[3] === 'reached' ? 'بلغ' : 'كان'} ${match[4]} ${match[5]}.`;
      match = value.match(/^(\d+) alarm occurrence\(s\) recorded$/);
      if (match) return `تم تسجيل ${match[1]} حالة إنذار`;
      match = value.match(/^Approximately ([\d.]+) running hours remain to the ([\d.]+)-hour interval\.$/);
      if (match) return `يتبقى نحو ${match[1]} ساعة تشغيل حتى موعد الصيانة عند ${match[2]} ساعة.`;
      const alarmParts = value.split(', ').map((part) => arabicCodes[part]);
      if (alarmParts.length && alarmParts.every(Boolean)) return alarmParts.join('، ');
      return value;
    };
    const formatCode = (value) => {
      if (value === null || value === undefined || value === '') return value;
      const normalized = String(value).toLowerCase();
      if (locale === 'ar') return messages.ar[normalized] || arabicCodes[normalized] || translateText(String(value));
      return messages.en[normalized] || normalized.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
    };
    return { locale, setLocale, t, translateText, formatCode,
      formatNumber: (value, options) => Number(value).toLocaleString(languageTag, options),
      formatDate: (value, options) => new Date(value).toLocaleDateString(languageTag, options),
      formatTime: (value, options) => new Date(value).toLocaleTimeString(languageTag, options),
    };
  }, [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useLocale() {
  const context = useContext(LocaleContext);
  if (!context) throw new Error('useLocale must be used inside LocaleProvider');
  return context;
}
